name: "Run CI Tests"
description: "Run the ci.sh script with the specified flags"
inputs:
    ci-flags:
      required: true
      description: "Flags with which to run the ci.sh tests"
    rs-version:
      required: true
      default: "stable"
      description: "Rust version with which to run the tests"

runs:
  using: "composite"
  steps:
    - name: Load Docker
      uses: ./.github/actions/load_docker
      if: ${{ env.TEST_DOCKER_IMAGE == 'parsec-openssl-provider-test' }}
      with:
        image-name: "${{ env.TEST_DOCKER_IMAGE }}"
        image-path: "/tmp"
    - name: Run the container to execute the test script
      run: docker run -v $(pwd):/tmp/parsec-openssl-provider -w /tmp/parsec-openssl-provider --env RUST_TOOLCHAIN_VERSION=${{ inputs.rs-version }} -t ${{ env.TEST_DOCKER_IMAGE }} /tmp/parsec-openssl-provider/tests/ci.sh --${{ inputs.ci-flags }} --create-keys
      shell: bash
